substitutions:
  name: hass-bt-proxy-02
  friendly_name: "Bluetooth Proxy #2"
  comment: AtomS3U ESP32S3 Development Kit with USB-A
  board: m5stack-atoms3

packages:
  common: !include packages/common-32-api.yaml

esp32:
  flash_size: 8MB
  variant: ESP32S3
  framework:
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

#binary_sensor:
#  - platform: gpio
#    pin:
#      number: GPIO41
#      inverted: true
#    name: Button

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO35
    num_leds: 1
    chipset: SK6812
    id: status_led
    name: Light
    restore_mode: ALWAYS_OFF