substitutions:
  name: hass-temp-02
  friendly_name: Temperature 02
  comment: esp32dev - MQTT - TMP117

esphome:
  name: ${name}
  comment: ${comment}

packages:
  mqtt: !include packages/common/mqtt.yaml
  sensors: !include packages/common/sensors.yaml
  ota: !include packages/common/ota.yaml
  text_sensor: !include packages/common/text_sensors.yaml
  binary_sensors: !include packages/common/binary_sensors.yaml
  logger: !include packages/common/logger.yaml
  buttons: !include packages/common/buttons.yaml

esp32:
  board: esp32dev

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  ssid: !secret wifi_ssid_lexit
#  password: !secret wifi_password_lexit

i2c:
  frequency: 800kHz
  scan: true
  sda: 22
  scl: 19

sensor:
- platform: tmp117
  name: "${friendly_name} Temperature"
  address: 0x48
  filters:
    - median:
        window_size: 4
        send_every: 2
        send_first_at: 2