substitutions:
  name: hass-sensor-02
  friendly_name: Sensor 02
  comment: D1 Mini - SHT30

packages:
  common: !include packages/common-8266.yaml
  
i2c:
  
sensor:
  - platform: sht3xd
    temperature:
      name: "${friendly_name} Temperature"
      filters:
      - median:
    humidity:
      name: "${friendly_name} Humidity"
      filters:
      - median:
    address: 0x45
    update_interval: 60s