substitutions:
  name: hass-screen-02
  friendly_name: Screen 02
  comment: Adafruit HUZZAH32 – Sonos Screen

packages:
  common: !include packages/common-32.yaml

external_components:
  - source: github://jenscski/esphome-components@main
    components: [ sh1107_base, sh1107_i2c ]

i2c:
  frequency: 800kHz
  scan: false

display:
  - platform: sh1107_i2c
    model: SH1107 64X128
    id: my_display
    rotation: 90
    contrast: 0.01
    pages:
      - id: p_idle
        lambda: |-
          if(!id(system_status).state)
          {
            it.print(128/2, 64/2, id(f_inter_l_12), TextAlign::CENTER, "Missing server");
          }
          else
          {
            if(!id(media_playing).state)
            {
              it.strftime(128/2, (64 - 14)/2, id(f_clock), COLOR_ON, TextAlign::CENTER, "%H:%M:%S", id(hass_time).now());
              if(!id(media_channel).state.empty())
                it.print(0, 64, id(f_inter_l_12), TextAlign::BOTTOM_LEFT, id(media_channel).state.c_str());
              else if(!id(media_artist).state.empty())
                it.print(0, 64, id(f_inter_l_12), TextAlign::BOTTOM_LEFT, id(media_artist).state.c_str());
            }
            else
            {
              int pos = 0;

              if(!id(media_channel).state.empty())
                it.print(0, 16 * pos++, id(f_inter_l_12), id(media_channel).state.c_str());

              if(!id(media_artist).state.empty())
                it.print(0, 16 * pos++, id(f_inter_l_12), id(media_artist).state.c_str());

              if(!id(media_title).state.empty())
                it.print(0, 16 * pos++, id(f_inter_l_12), id(media_title).state.c_str());
                
              if(!id(media_album).state.empty())
                it.print(0, 16 * pos++, id(f_inter_l_12), id(media_album).state.c_str());

              it.strftime(0, 64, id(f_clock_small), COLOR_ON, TextAlign::BOTTOM_LEFT, "%H:%M:%S", id(hass_time).now());
            }

            // footer
            int w = 35;
            int h = 14;
            it.filled_rectangle(128 - w, 64 - h, w, h, COLOR_OFF);
            it.printf(128 - 13, 64, id(f_inter_l_12), TextAlign::BOTTOM_RIGHT, "%d", (int)id(media_volume).state);
            it.print(128,       64, id(f_mdi_12),     TextAlign::BOTTOM_RIGHT, id(media_muted).state ? "\U000F0581" : "\U000F057E");
            it.line(0, 64 - 15, 128, 64 - 15);
          }

font:
  - file: fonts/Inter-Light.ttf
    size: 12
    id: f_inter_l_12
    glyphs: '!''&"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÆØÅÄÖ abcdefghijklmnopqrstuvwxyzæøåäö'
  - file: fonts/AzeretMono-Medium.ttf
    id: f_clock
    size: 24
    glyphs: '0123456789:'
  - file: fonts/AzeretMono-Medium.ttf
    id: f_clock_small
    size: 12
    glyphs: '0123456789:'
  - file: fonts/materialdesignicons-webfont.ttf
    size: 12
    id: f_mdi_12
    glyphs:
      - "\U000F057E" # mdi-volume-high
      - "\U000F0581" # mdi-volume-off

text_sensor:
  - platform: homeassistant
    id: media_artist
    entity_id: sensor.media_artist
    internal: true
    on_value:
      then:
        - component.update: my_display
  - platform: homeassistant
    id: media_channel
    entity_id: sensor.media_channel
    internal: true
    on_value:
      then:
        - component.update: my_display
  - platform: homeassistant
    id: media_title
    entity_id: sensor.media_title
    internal: true
    on_value:
      then:
        - component.update: my_display
  - platform: homeassistant
    id: media_album
    entity_id: sensor.media_album
    internal: true
    on_value:
      then:
        - component.update: my_display
sensor:
  - platform: homeassistant
    id: media_volume
    entity_id: sensor.media_volume
    internal: true
    on_value:
      then:
        - component.update: my_display

binary_sensor:
  - platform: homeassistant
    id: media_playing
    entity_id: sensor.media_playing
    internal: true
    on_state:
      then:
        - component.update: my_display
  - platform: homeassistant
    id: media_muted
    entity_id: sensor.media_muted
    internal: true
    on_state:
      then:
        - component.update: my_display