substitutions:
  name: hass-clock-02
  friendly_name: "Clock #2"
  comment: ATOM Lite ESP32 - Clock
  board: m5stack-atom

packages:
  common: !include packages/common-32-api.yaml
  
number:
  - platform: template
    id: brightness
    name: "Brightness"
    icon: mdi:brightness-5
    step: 1
    min_value: 0
    max_value: 255
    optimistic: true
    initial_value: 255
    restore_value: true

uart:
  tx_pin: GPIO26
  baud_rate: 9600
  
interval:
  - interval: 1s
    then:
      - uart.write: !lambda
          auto b = id(brightness).state;
          return {(uint8_t)0x7a, (uint8_t)b};
      - uart.write: [0x77, 0x02]
      - uart.write: [0x79, 0x00]
      - uart.write: !lambda
          auto s = id(hass_time).now().strftime("%H%M");
          return std::vector<uint8_t>( s.begin(), s.end() );
          