substitutions:
  name: hass-sensecap-kitchen
  friendly_name: "SenseCAP Kitchen"
  comment: Seeed SenseCap Indicator
  board: esp32-s3-devkitc-1

packages:
  common: !include packages/common-32-api.yaml

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

wifi:
  use_address: 192.168.30.21

api:
  on_client_connected:
    - lvgl.widget.show: lbl_hastatus
    - logger.log:
        format: "Client %s connected to API with IP %s"
        args: ["client_info.c_str()", "client_address.c_str()"]
  on_client_disconnected:
    then:
      - if:
          condition:
            not:
              api.connected:
          then:
            - lvgl.widget.hide: lbl_hastatus

time:
  - platform: homeassistant
    id: !extend hass_time
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: lbl_clock
          text: !lambda |-
            return id(hass_time).now().strftime("%H:%M").c_str();

sensor:
  - platform: homeassistant
    id: temperature_outdoor
    entity_id: sensor.hass_outdoor_temp_01_temperature
    internal: true
    on_value:
      - lvgl.label.update:
          id: lbl_temperature_outdoor
          text:
            format: "%.1f°C"
            args: [ 'x' ]
  - platform: homeassistant
    id: temperature_kitchen
    entity_id: sensor.kjokken_sensor_1_temperature
    internal: true
    on_value:
      - lvgl.label.update:
          id: lbl_temperature_kitchen
          text:
            format: "%.1f°C"
            args: [ 'x' ]

text_sensor:
  - platform: homeassistant
    id: light_martin
    entity_id: light.silicon_labs_ezsp_martin_taklys
    internal: true
    on_value:
      - logger.log:
          format: "Changed: %s"
          args: [ 'x' ]
      - lvgl.label.update:
          id: lbl_lightbulb_martin
          state:
            checked: !lambda return (0 == x.compare(std::string{"on"}));
          text: !lambda |-
            static char buf[10];
            std::string icon;
            if (0 == x.compare(std::string{"on"})) {
                icon = "\U000F0335";
            } else {
                icon = "\U000F0336";
            }
            snprintf(buf, sizeof(buf), "%s", icon.c_str());
            return buf;
  - platform: homeassistant
    id: light_eivind
    entity_id: light.eivind_taklys_light
    internal: true
    on_value:
      - logger.log:
          format: "Changed: %s"
          args: [ 'x' ]
      - lvgl.label.update:
          id: lbl_lightbulb_eivind
          state:
            checked: !lambda return (0 == x.compare(std::string{"on"}));
          text: !lambda |-
            static char buf[10];
            std::string icon;
            if (0 == x.compare(std::string{"on"})) {
                icon = "\U000F0335";
            } else {
                icon = "\U000F0336";
            }
            snprintf(buf, sizeof(buf), "%s", icon.c_str());
            return buf;
  - platform: homeassistant
    id: light_kitchen
    entity_id: light.kjokken_powerplugg_1_switch
    internal: true
    on_value:
      - logger.log:
          format: "Changed: %s"
          args: [ 'x' ]
      - lvgl.label.update:
          id: lbl_lightbulb_kitchen
          state:
            checked: !lambda return (0 == x.compare(std::string{"on"}));
          text: !lambda |-
            static char buf[10];
            std::string icon;
            if (0 == x.compare(std::string{"on"})) {
                icon = "\U000F0335";
            } else {
                icon = "\U000F0336";
            }
            snprintf(buf, sizeof(buf), "%s", icon.c_str());
            return buf;

psram:
  mode: octal
  speed: 80MHz

output:
  - platform: ledc
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: ledc_gpio45
    frequency: 100Hz

i2c:
  - id: bus_a
    sda: GPIO39
    scl: GPIO40
    scan: false

spi:
  - id: lcd_spi
    clk_pin: GPIO41
    mosi_pin: GPIO48

pca9554:
  - id: pca9554a_device
    address: 0x20
    pin_count: 16

display:
  - platform: st7701s
    id: sensecap_display
    auto_clear_enabled: false
    data_rate: 4MHz
    update_interval: never
    spi_mode: MODE3
    color_order: RGB
    dimensions:
      width: 480
      height: 480
    invert_colors: true
    transform:
      mirror_x: true
      mirror_y: true
    cs_pin:
      pca9554: pca9554a_device
      number: 4
    reset_pin:
      pca9554: pca9554a_device
      number: 5
    de_pin: GPIO18
    hsync_pin: GPIO16
    vsync_pin: GPIO17
    pclk_pin: GPIO21
    init_sequence:
      - 1 # select canned init sequence number 1
      - delay 5ms
      - [0xE0, 0x1F] # Set sunlight readable enhancement
    data_pins:
      red:
        - GPIO4 #r1
        - GPIO3 #r2
        - GPIO2 #r3
        - GPIO1 #r4
        - GPIO0 #r5
      green:
        - GPIO10 #g0
        - GPIO9 #g1
        - GPIO8 #g2
        - GPIO7 #g3
        - GPIO6 #g4
        - GPIO5 #g5
      blue:
        - GPIO15 #b1
        - GPIO14 #b2
        - GPIO13 #b3
        - GPIO12 #b4
        - GPIO11 #b5

light:
  - platform: monochromatic
    name: "Backlight"
    id: backlight
    output: ledc_gpio45
    restore_mode: ALWAYS_ON

touchscreen:
  platform: ft5x06
  id: sensecap_touchscreen
  transform:
    mirror_x: true
    mirror_y: true

# Basic Config
image:
  - file: https://esphome.io/favicon-512x512.png
    id: boot_logo
    resize: 200x200
    type: RGB565
    transparency: alpha_channel
  - file: bg.jpg
    id: img_bg
    type: RGB565

lvgl:
  disp_bg_image: img_bg
  theme:
    button:
      bg_color: 0x444444
      shadow_width: 0
      border_opa: COVER
      border_width: 1
      border_color: 0x666666
    obj:
      border_opa: COVER
      border_width: 1
      border_color: 0x666666
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x0000FF
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30
  top_layer:
    widgets:
      - label:
          id: lbl_clock
          text: '--:--'
          text_color: 0xffffff
          text_font: f_24
          x: 20
          y: 20
      - label:
          text: "\uF1EB"
          id: lbl_hastatus
          align: top_right
          text_font: montserrat_24 
          x: -20
          y: 20
          text_align: right
          text_color: 0xFFFFFF
          hidden: true
  pages:
    - id: main_page
      bg_opa: TRANSP
      widgets:
        - obj:
            bg_opa: TRANSP
            width: 210
            height: SIZE_CONTENT
            x: 20
            y: 100
            widgets:
              - label:
                  text: 'Utendørs'
                  text_font: f_24
                  text_color: 0xffffff
              - label:
                  id: lbl_temperature_outdoor
                  text: '--.-°C'
                  width: 100%
                  text_align: CENTER
                  text_font: f_48
                  text_color: 0xffffff
                  y: 30
        - obj:
            bg_opa: TRANSP
            width: 210
            height: SIZE_CONTENT
            x: 250
            y: 100
            widgets:
              - label:
                  text: 'Kjøkken'
                  text_font: f_24
                  text_color: 0xffffff
              - label:
                  id: lbl_temperature_kitchen
                  text: '--.-°C'
                  width: 100%
                  text_align: CENTER
                  text_font: f_48
                  text_color: 0xffffff
                  y: 30
        - button:
            x: 20
            y: -20
            width: 60
            height: 60
            align: BOTTOM_LEFT
            id: btn_lightbulb_kitchen
            widgets:
              - label:
                  id: lbl_lightbulb_kitchen
                  align: CENTER
                  text_font: mdi_42
                  text: "\U000F0336" # mdi-lightbulb-outline
                  text_color: 0xffffff    
                  checked:
                    text_color: 0xffea00
            on_short_click:
              - logger.log: 'Clicked'
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.kjokken_powerplugg_1_switch
        - button:
            x: 100
            y: -20
            width: 60
            height: 60
            align: BOTTOM_LEFT
            id: btn_lightbulb_martin
            widgets:
              - label:
                  id: lbl_lightbulb_martin
                  align: CENTER
                  text_font: mdi_42
                  text: "\U000F0336" # mdi-lightbulb-outline
                  text_color: 0xffffff    
                  checked:
                    text_color: 0xffea00
            on_short_click:
              - logger.log: 'Clicked'
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.silicon_labs_ezsp_martin_taklys
        - button:
            x: 180
            y: -20
            width: 60
            height: 60
            align: BOTTOM_LEFT
            id: btn_lightbulb_eivind
            widgets:
              - label:
                  id: lbl_lightbulb_eivind
                  align: CENTER
                  text_font: mdi_42
                  text: "\U000F0336" # mdi-lightbulb-outline
                  text_color: 0xffffff    
                  checked:
                    text_color: 0xffea00
            on_short_click:
              - logger.log: 'Clicked'
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.eivind_taklys_light
font:
  - file: gfonts://Montserrat@Medium
    size: 24
    bpp: 4
    id: f_24
    glyphsets:
      - GF_Latin_Core
  - file: gfonts://Montserrat@Medium
    size: 48
    bpp: 4
    id: f_48
    glyphsets:
      - GF_Latin_Core
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: mdi_42
    size: 42
    bpp: 4
    glyphs: [
      "\U000F0335", # mdi-lightbulb
      "\U000F0336", # mdi-lightbulb-outline
      ]