substitutions:
  name: mqtt-work-02
  friendly_name: "[MQTT] Jobb #2"
  comment: ATOMS3 Dev Kit w/ 0.85-inch Screen
  board: m5stack-atoms3

packages:
  common: !include packages/common-32-mqtt.yaml

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_lexit
  password: !secret wifi_password_lexit

one_wire:
  - platform: gpio
    pin: GPIO38

sensor:
- platform: dallas_temp
  name: "Temperature"
#  index: 0
  filters:
    - median:
        window_size: 4
        send_every: 2
        send_first_at: 2
  on_value:
    - lvgl.label.update:
        id: fld_temperature
        text:
          format: "%.2f°"
          args: [x]

switch:
  - platform: gpio
    pin: 16
    name: "Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

spi:
  clk_pin: GPIO17
  mosi_pin: GPIO21

display:
  - platform: ili9xxx
    id: my_display
    update_interval: 1s
    model: ST7789V
    cs_pin: 15
    dc_pin: 33
    reset_pin: 34
    rotation: 180
    invert_colors: true
    auto_clear_enabled: False
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2

lvgl:
  pages:
    - id: main_page
      widgets:
      - label:
          align: CENTER
          id: fld_temperature
          text_font: f_temperature
          text: "--.--°"
      - label:
          id: fld_clock
          align: BOTTOM_MID
          text_font: f_clock
          text: "--:--:--"

time:
  - platform: sntp
    id: time_comp
    on_time_sync:
      - lvgl.label.update:
          id: fld_clock
          text:
            time_format: "%H.%M.%S"
    on_time:
      - seconds: '*'
        then:
          - lvgl.label.update:
              id: fld_clock
              text:
                time_format: "%H.%M.%S"

font:
  - file: fonts/materialdesignicons-webfont.ttf
    id: f_mdi
    bpp: 4
    size: 16
    glyphs:
      - "\U000F0C5F" # mdi-close-network-outline
      - "\U000F0C54" # mdi-check-network-outline
  - file: gfonts://Azeret Mono@Medium
    id: f_clock
    bpp: 4
    size: 24
    glyphs: '-0123456789:.'
  - file: gfonts://Azeret Mono@Medium
    id: f_temperature
    bpp: 4
    size: 32
    glyphs: -0123456789.°