substitutions:
  name: mqtt-atoms3-02
  friendly_name: "[MQTT] AtomS3 Lite #2"
  comment: ATOMS3 Dev Kit w/ 0.85-inch Screen
  board: m5stack-atoms3

packages:
  common: !include packages/common-32-mqtt.yaml

time:
  - platform: sntp

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_lexit
  password: !secret wifi_password_lexit