substitutions:
  name: mqtt-atoms3-01
  friendly_name: "[MQTT] AtomS3 Lite #1"
  comment: ATOMS3 Dev Kit w/ 0.85-inch Screen
  board: m5stack-atoms3

packages:
  common: !include packages/common-32-mqtt.yaml

time:
  - platform: sntp
    id: time_comp
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update
      - seconds: '*'
        then:
          - lvgl.label.update:
              id: fld_clock
              text:
                time_format: "%H.%M.%S"

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_lexit
  password: !secret wifi_password_lexit

binary_sensor:
  - platform: gpio
    name: Button
    on_click: 
      then:
      - lvgl.page.next:
          animation: OUT_LEFT
          time: 500ms
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true

spi:
  clk_pin: GPIO17
  mosi_pin: GPIO21

image:
  - file: 'lilje2.png'
    id: my_image
    type: RGB565
    transparency: True

switch:
  - platform: gpio
    pin: 16
    name: "Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    id: my_display
    update_interval: 1s
    model: ST7789V
    cs_pin: 15
    dc_pin: 33
    reset_pin: 34
    rotation: 180
    invert_colors: true
    auto_clear_enabled: False
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2
#    pages:
#      - id: page1
#        lambda: |-
#          it.image(0, 0, id(my_image));

lvgl:
  pages:
    - id: main_page
      widgets:
      - label:
          x: 0
          y: 0
          width: 128
          text_font: f_media_4
          long_mode: SCROLL
          text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      - label:
          id: fld_clock
          align: CENTER
          text: '--.--.--'
          text_font: f_media_4
          long_mode: SCROLL
    - id: clock_page
      widgets:
        - obj: # clock container
            height: 128
            width: 128
            align: CENTER
            pad_all: 0
            border_width: 0
            bg_color: 0xFFFFFF
            widgets:
              - meter: # clock face
                  height: 128
                  width: 128
                  align: CENTER
                  bg_opa: TRANSP
                  border_width: 0
                  text_color: 0x000000
                  scales:
                    - range_from: 0 # minutes scale
                      range_to: 60
                      angle_range: 360
                      rotation: 270
                      ticks:
                        width: 1
                        count: 61
                        length: 10
                        color: 0x000000
                      indicators:
                        - line:
                            id: minute_hand
                            width: 3
                            color: 0xa6a6a6
                            r_mod: -4
                            value: 0
                    - range_from: 1 # hours scale for labels
                      range_to: 12
                      angle_range: 330
                      rotation: 300
                      ticks:
                        width: 1
                        count: 12
                        length: 1
                        major:
                          stride: 1
                          width: 4
                          length: 10
                          color: 0xC0C0C0
                          label_gap: 12
                    - range_from: 0 # hi-res hours scale for hand
                      range_to: 720
                      angle_range: 360
                      rotation: 270
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: hour_hand
                            width: 5
                            color: 0xa6a6a6
                            r_mod: -30
                            value: 0
    - id: spinner_page
      widgets:
      - spinner:
          align: CENTER
          height: 50
          width: 50
          spin_time: 1s
          arc_length: 60deg
          arc_width: 8
          indicator:
            arc_color: 0x18bcf2
            arc_width: 8
    - id: image_page
      widgets:
      - image:
          src: my_image
          align: CENTER

script:
  - id: time_update
    then:
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda |-
            return id(time_comp).now().minute;
      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(time_comp).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;

font:
  - file: gfonts://Ubuntu@Regular
    size: 20
    id: f_media_4
    bpp: 4
    glyphs: '÷!''&«»?#"%’^´()+•=,-_.:/°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz¡¿·ÄäÀàÁáÂâÃãÅåǍǎĄąĂăÆæĀāÇçĆćĈĉČčĎđĐďðÈèÉéÊêËëĚěĘęĖėĒēĜĝĢģĞğĤĥÌìÍíÎîÏïıĪīĮįĴĵĶķĹĺĻļŁłĽľĿŀÑñŃńŇňŅņÖöÒòÓóÔôÕõŐőØøŒœŔŕŘřẞßŚśŜŝŞşŠšȘșŤťŢţÞþȚțÜüÙùÚúÛûŰűŨũŲųŮůŪūŴŵÝýŸÿŶŷŹźŽžŻż'