substitutions:
  name: wt32sc01b
  id_prefix: "wt32sc01b"
  friendly_name: 'WT32-SC01 3.5"'
  comment: WT32-SC01 3.5"
  board: esp-wrover-kit

packages:
  common: !include packages/common-32-mqtt.yaml

esp32:
  flash_size: 16MB
#  framework:
#    sdkconfig_options:
#      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y

psram:
  mode: quad
  speed: 80MHz

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_lexit
  password: !secret wifi_password_lexit

output:
  - platform: ledc
    pin: GPIO23
    id: gpio_23_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_23_backlight_pwm
    name: "${friendly_name} backlight"
    id: ${id_prefix}_backlight
    restore_mode: ALWAYS_ON

preferences:
  flash_write_interval: 15min

i2c:
  id: i2c_bus_intern
  sda: 18
  scl: 19
  scan: false

touchscreen:
  - platform: ft63x6
    id: ${id_prefix}_touch
    i2c_id: i2c_bus_intern
    interrupt_pin: GPIO39

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

display:
  - platform: ili9xxx
    id: ${id_prefix}_display
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
#    rotation: 270
    invert_colors: false
    auto_clear_enabled: False
    update_interval: never
      
lvgl:
  displays:
    - ${id_prefix}_display
  touchscreens:
    - ${id_prefix}_touch
  top_layer:
    widgets:
      - buttonmatrix:
          align: bottom_mid
          pad_all: 0
          pad_row: 0
          pad_column: 0
          outline_width: 0
          border_width: 2
          border_color: 0xff0000
          border_opa: COVER
          width: 99

          bg_color: 0x00ff00
          bg_opa: COVER

          items:
            bg_color: 0x0000ff
            bg_opa: COVER
            pad_all: 0
            outline_width: 0

          id: top_layer
          rows:
            - buttons:
              - id: page_prev
                text: "\uF053"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: main_page
              - id: page_next
                text: "\uF054"
                on_press:
                  then:
                    lvgl.page.next:
  pages:
    - id: main_page
      widgets:
        - button:
            x: 20
            y: 20
            width: 70
            height: 30
        - label:
            align: CENTER
            text: 'Hello World!'
        - buttonmatrix:
            align: TOP_MID
            pad_all: 0
            outline_width: 0
            id: top_layer2
            rows:
              - buttons:
                - id: page_prev2
                  text: "\uF053"
                  on_press:
                    then:
                      lvgl.page.previous:
                - id: page_home2
                  text: "\uF015"
                  on_press:
                    then:
                      lvgl.page.show: main_page
                - id: page_next2
                  text: "\uF054"
                  on_press:
                    then:
                      lvgl.page.next: