substitutions:
  name: wt32sc01a
  friendly_name: 'WT32-SC01 3.5"'
  comment: WT32-SC01 3.5"
  board: esp-wrover-kit

packages:
  common: !include packages/common-32-api.yaml

esp32:
  flash_size: 16MB
#  framework:
#    sdkconfig_options:
#      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

preferences:
  flash_write_interval: 15min

psram:
  mode: quad
  speed: 80MHz

output:
  - platform: ledc
    pin: GPIO23
    id: gpio_23_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_23_backlight_pwm
    name: "${friendly_name} backlight"
    restore_mode: ALWAYS_ON

i2c:
  id: i2c_bus_intern
  sda: 18
  scl: 19
  scan: false

touchscreen:
  - platform: ft63x6
    id: wt32sc01a_touch
    i2c_id: i2c_bus_intern
    interrupt_pin: GPIO39

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: 
      number: GPIO12
      ignore_strapping_warning: true
      
display:
  - platform: ili9xxx
    id: wt32sc01a_display
    model: ST7796
    cs_pin:
      number: GPIO15
      ignore_strapping_warning: true
    dc_pin: GPIO21
    reset_pin: GPIO22
    invert_colors: false
    auto_clear_enabled: False
    update_interval: never
      
lvgl:
#  displays:
#    - wt32sc01a_display
#  touchscreens:
#    - wt32sc01a_touch
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x0000FF
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30
  pages:
    - id: main_page
      widgets:
        - obj:
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "ESPHome LVGL Display"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF