esphome:
  name: foo-bar
  friendly_name: foo-bar

esp32:
  board: m5stack-atom
  flash_size: 4MB
  framework:
#    type: arduino
#    version: 2.0.17
    type: esp-idf
#    version: 5.3.0
#    platform_version: platformio/espressif32@6.8.1
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Enable logging
logger:

ethernet:
  type: W5500
  clk_pin: GPIO22
  cs_pin: GPIO19
  miso_pin: GPIO23
  mosi_pin: GPIO33

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_channel: 0
    chipset: SK6812
    id: status_led
    name: Light
    restore_mode: ALWAYS_ON
