substitutions:
  name: hass-screen-01
  friendly_name: "Screen #1"
  comment: Adafruit HUZZAH32 – Sonos Screen Stua (LVGL)
  board: featheresp32

packages:
  common: !include packages/common-32-api.yaml

esp32:
  framework:
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

status_led:
  pin:
    number: LED

external_components:
  - source: github://jenscski/esphome-components@main
    refresh: 1h
    components: [ sh1107_base, sh1107_i2c ]

i2c:
  frequency: 800kHz
  scan: false

display:
  - platform: sh1107_i2c
    model: SH1107 64X128
    id: my_display
    rotation: 90
    contrast: 1%
    auto_clear_enabled: False

lvgl:
  pages:
    - id: page_offline
      widgets:
        - label:
            align: CENTER
            text_font: f_media
            text: '\U000F0C5F'
    - id: page2
      widgets:
        - label:
            x: 0
            y: 0
            width: 100%
            text_font: f_media
            text: 'Hello World!'    
            long_mode: SCROLL_CIRCULAR
        - label:
            x: 0
            y: 16
            width: 100%
            text_font: f_media
            text: 'Hello World!'    
            long_mode: SCROLL_CIRCULAR
        - label:
            x: 0
            y: 32
            width: 100%
            text_font: f_media
            text: 'Hello World!'    
            long_mode: SCROLL_CIRCULAR

# https://maximilian.schalch.de/2018/05/complete-list-of-european-special-characters/
font:
  - file: gfonts://Ubuntu@Regular
    size: 14
    bpp: 2
    id: f_media
    glyphsets:
      - GF_Latin_Core
  - file: gfonts://Azeret Mono@Medium
    id: f_clock
    size: 32
    bpp: 2
    glyphs: '0123456789:'
  - file: gfonts://Azeret Mono@Light
    id: f_clock_small
    size: 12
    bpp: 2
    glyphs: '0123456789:'
  - file: fonts/materialdesignicons-webfont.ttf
    size: 12
    bpp: 2
    id: f_mdi_12
    glyphs:
      - "\U000F057E" # mdi-volume-high
      - "\U000F0581" # mdi-volume-off
  - file: fonts/materialdesignicons-webfont.ttf
    size: 64
    bpp: 2
    id: f_mdi_64
    glyphs:
      - "\U000F0C5F" # mdi-close-network-outline

text_sensor:
  - platform: homeassistant
    id: media_artist
    entity_id: sensor.media_artist_stua
    internal: true
  - platform: homeassistant
    id: media_channel
    entity_id: sensor.media_channel_stua
    internal: true
  - platform: homeassistant
    id: media_title
    entity_id: sensor.media_title_stua
    internal: true
  - platform: homeassistant
    id: media_album
    entity_id: sensor.media_album_stua
    internal: true

sensor:
  - platform: homeassistant
    id: media_volume
    entity_id: sensor.media_volume_stua
    internal: true

binary_sensor:
  - platform: homeassistant
    id: media_playing
    entity_id: sensor.media_playing_stua
    internal: true
  - platform: homeassistant
    id: media_muted
    entity_id: sensor.media_muted_stua
    internal: true
