substitutions:
  name: hass-temp-01
  friendly_name: Jobb 01
  comment: NodeMCU - MQTT - DS18B20

esphome:
  name: ${name}
  comment: ${comment}
  friendly_name: ${friendly_name}

packages:
  mqtt: !include packages/common/mqtt.yaml
  sensors: !include packages/common/sensors.yaml
  ota: !include packages/common/ota.yaml
  text_sensor: !include packages/common/text_sensors.yaml
  binary_sensors: !include packages/common/binary_sensors.yaml
  logger: !include packages/common/logger.yaml
  buttons: !include packages/common/buttons.yaml

esp8266:
  board: nodemcuv2
  restore_from_flash: true
  
one_wire:
  - platform: gpio
    pin: D4

http_request:
  useragent: esphome/device
  verify_ssl: false
  timeout: 10s

ota:
  - platform: http_request

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_lexit
  password: !secret wifi_password_lexit

binary_sensor:
- platform: gpio
  name: Button
  pin:
    number: D3
    inverted: true
    mode:
      input: true
      pullup: true

sensor:
- platform: dallas_temp
  name: "Temperature"
#  index: 0
  filters:
    - median:
        window_size: 4
        send_every: 2
        send_first_at: 2

status_led:
  pin:
    number: LED
    inverted: true

button:
  - platform: template
    name: "Firmware update"
    on_press:
      then:
        - ota.http_request.flash:
            md5_url: https://ota.skibakk.net/hass-temp-01.md5
            url: https://ota.skibakk.net/hass-temp-01.bin
        - logger.log: "This message should be not displayed(reboot)"
