substitutions:
  name: hass-bt-proxy-03
  friendly_name: Bluetooth Proxy 03
  comment: AtomS3 Lite ESP32S3 Dev Kit
  board: m5stack-atom

packages:
  common: !include packages/common-32.yaml

wifi: !remove

sensor:
  - id: !remove wifi_signal_sensor

text_sensor: !remove

ethernet:
  type: W5500
  clk_pin: GPIO22
  cs_pin: GPIO19
  miso_pin: GPIO23
  mosi_pin: GPIO33

esp32:
  flash_size: 4MB
#  variant: ESP32S3
  framework:
    type: arduino
    version: 2.0.17
#    sdkconfig_options:
#      COMPILER_OPTIMIZATION_SIZE: y
#      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

#esp32_ble_tracker:
#  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
#    active: true

#bluetooth_proxy:
#  active: true
