substitutions:
  name: mqtt-atom-02
  friendly_name: "[MQTT] Atom Lite #1"
  comment: ATOM Lite ESP32 IoT Development Kit

packages:
  common: !include packages/common-32.yaml
  mqtt: !include packages/common/mqtt.yaml

ota: !remove
api: !remove
time: !remove

esp32:
  board: m5stack-atom
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: 6.8.1
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_lexit
  password: !secret wifi_password_lexit

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_channel: 0
    chipset: SK6812
    id: status_led
    name: Light
    restore_mode: ALWAYS_ON
    effects:
      - random:
      - flicker:
      - addressable_rainbow: