esphome:
  name: test-atom-wifi
  comment: ATOM Lite ESP32
  friendly_name: '[Test] ATOM Lite ESP32'

esp32:
  board: m5stack-atom
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: platformio/espressif32@6.8.1

logger:

wifi:
  fast_connect: true
  networks:
  - ssid: labbing
    password: "w*K@62wFLC6N"

web_server:
  local: True

sensor:
- platform: uptime
  name: Uptime
  id: uptime_sensor
  device_class: duration
  disabled_by_default: false
  force_update: false
  unit_of_measurement: s
  icon: mdi:timer-outline
  accuracy_decimals: 0
  state_class: total_increasing
  entity_category: diagnostic
  update_interval: 60s
  type: seconds
- platform: wifi_signal
  name: WiFi Signal
  update_interval: 60s
  id: wifi_signal_sensor
  filters:
  - median:
      window_size: 5
      send_every: 5
      send_first_at: 1
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
  entity_category: diagnostic
- platform: template
  name: Free heap
  lambda: !lambda |-
    return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
  icon: mdi:memory
  entity_category: diagnostic
  state_class: measurement
  unit_of_measurement: b
  update_interval: 60s
  disabled_by_default: false
  force_update: false
  accuracy_decimals: 1
text_sensor:
- platform: wifi_info
  ip_address:
    name: IP Address
    id: wifi_info_ip_address_sensor
    disabled_by_default: false
    entity_category: diagnostic
    update_interval: 1s
  ssid:
    name: SSID
    id: wifi_info_ssid_sensor
    disabled_by_default: false
    entity_category: diagnostic
    update_interval: 1s
- platform: version
  name: Version
  hide_timestamp: true
  disabled_by_default: false
  icon: mdi:new-box
  entity_category: diagnostic
binary_sensor:
- platform: status
  name: Node Status
  id: system_status
  disabled_by_default: false
  entity_category: diagnostic
  device_class: connectivity
- platform: gpio
  pin:
    number: GPIO39
    inverted: true
  name: Button
button:
- platform: restart
  name: Restart
  id: restart_button
  disabled_by_default: false
  icon: mdi:restart
  entity_category: config
  device_class: restart

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_channel: 0
    chipset: SK6812
    id: status_led
    name: Light
    effects:
      - random:
      - flicker:
      - addressable_rainbow: