---
substitutions:
  wifi_reboot_timeout: 5min

wifi:
  # use_address: $ip
  reboot_timeout: $wifi_reboot_timeout
#  fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 0.0