---
substitutions:

esp32:
  board: ${board}
  framework:
    type: arduino
    version: 2.0.6
    platform_version: 5.3.0

packages:
  base: !include common-base.yaml

sensor:
  - platform: template
    name: "${friendly_name} Free heap"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
