---
substitutions:

#external_components:
#  - source: github://jenscski/esphome@esp32
#    refresh: 1s
#    components: [ esp32 ]

esp32:
  board: ${board}
  framework:
    type: esp-idf
    version: latest
#    version: 5.5.1
#    platform_version: 55.03.32
#    version: 5.3.1
#    platform_version: 6.9.0

sensor:
  - platform: template
    name: "Free heap"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
