---
esphome:
  name: ${name}
  comment: ${comment}
  friendly_name: ${friendly_name}

packages:
  wifi: !include common/wifi.yaml
  sensors: !include common/sensors.yaml
  text_sensor: !include common/text_sensors.yaml
  binary_sensors: !include common/binary_sensors.yaml
  logger: !include common/logger.yaml
  switches: !include common/switches.yaml
  buttons: !include common/buttons.yaml