---
esphome:
  name: ${name}
  comment: ${comment}
  friendly_name: ${friendly_name}

packages:
  base: !include common-base.yaml
  ota: !include common/ota.yaml
  time: !include common/time.yaml
  api: !include common/api.yaml